name: Release

on:
  # manual trigger
  workflow_dispatch:
    inputs:
      bumpType:
        description: 'Bump type (path, minor, major)'
        required: true
        default: 'patch'

jobs:
  release:
    runs-on: self-hosted
    env:
      NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
    steps:
      - name: Checkout code into workspace directory
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Install yarn
        run: npm install --global yarn

      - name: Install dependency
        run: yarn install

      - name: Set npm auth
        run: yarn run set-npm-auth

      - name: Release
        run: yarn run release -- --release-as ${{ github.event.inputs.bumpType }}

      - name: Build
        run: yarn run build

      - name: Publish
        run: git push --follow-tags origin master && cd dist && yarn run publish
